
-- Este script é executado automaticamente pelo Spring Boot para inserir dados iniciais no banco de dados.

insert into produto values
(1, 'Sanduiches de Boi', 'Hamburguer', 14.5),
(2, 'Sanduiches de Boi', 'X - Burguer', 16.0),
(3, 'Sanduiches de Boi', 'X - Egg Burguer', 17.0),
(4, 'Sanduiches de Boi', 'X - Bacon', 17.0),
(5, 'Sanduiches de Boi', 'X - Egg Bacon', 18.0),
(6, 'Sanduiches de Boi', 'Laçador', 18.0),
(7, 'Sanduiches de Boi', 'X - Tudo', 20.0),
(8, 'Sanduiches de Frango', 'Frango Light', 17.50),
(9, 'Sanduiches de Frango', 'X - Frango', 12.0),
(10, 'Sanduiches de Frango', 'X - Egg Frango', 13.8),
(11, 'Sanduiches de Frango', 'Bacon Frango', 15.50),
(12, 'Sanduiches de Frango', 'X - Egg Bacon Frango', 16.5),
(13, 'Sanduiches de Frango', 'Frango a Catupiry', 18.0),
(14, 'Sanduiches de Frango', 'X - Salada Frango', 16.0),
(15, 'Sanduiches Diversos', 'Misto Quente', 6.0),
(16, 'Sanduiches Diversos', 'Mistão', 8.5),
(17, 'Sanduiches Diversos', 'Vegetariano', 16.0),
(18, 'Sanduiches Especiais', 'Especial da Casa', 24.4),
(19, 'Sanduiches Especiais', 'Hamburguer de Picanha', 21.0),
(20, 'Sanduiches Especiais', 'X - Picanha', 22.0),
(21, 'Sanduiches Especiais', 'X - Egg Picanha', 22.50),
(22, 'Sanduiches Especiais', 'X - Egg Bacon Picanha', 23),
(23, 'Sanduiches Especiais', 'Picanha a Catupiry', 23),
(24, 'Sanduiches Especiais', 'Filé Mignon Burguer', 20),
(25, 'Sanduiches Especiais', 'X - Filé Mignon', 20),
(26, 'Sanduiches Especiais', 'X - Egg Filé Mignon', 22),
(27, 'Sanduiches Especiais', 'X - Egg Bacon Filé Mignon', 24.5),
(28, 'Sanduiches Especiais', 'Filé Mignon a Catupiry', 24.5),
(29, 'Pizzas', 'Pizza Bacon e Milho', 31.9),
(30, 'Pizzas', 'Pizza Mussarela', 31.9),
(31, 'Pizzas', 'Pizza Napolitana', 31.9),
(32, 'Pizzas', 'Pizza Presunto', 31.9),
(33, 'Pizzas', 'Pizza Marguerita', 31.9),
(34, 'Pizzas', 'Pizza Banana', 31.9),
(35, 'Pizzas', 'Pizza Quatro Queijos', 31.9),
(36, 'Pizzas', 'Pizza Calabresa', 31.9),
(37, 'Pizzas', 'Pizza A Moda', 42.9),
(38, 'Pizzas', 'Pizza Frango a Catupiry', 42.9),
(39, 'Pizzas', 'Pizza Portuguesa', 42.9),
(40, 'Pizzas', 'Pizza Champignon', 42.9),
(41, 'Pizzas', 'Pizza Peperone', 42.9),
(42, 'Pizzas', 'Pizza Nordestina', 42.9),
(43, 'Pizzas', 'Pizza Frago a Bolonhesa', 42.9),
(44, 'Pizzas', 'Pizza Lombo Canadense', 42.9),
(45, 'Pizzas', 'Pizza Quatro Carnes', 42.9),
(46, 'Pizzas', 'Pizza Salaminho', 42.9),
(47, 'Pizzas', 'Pizza Atum', 42.9),
(48, 'Pizzas', 'Pizza Vegetariana', 42.9),
(49, 'Pizzas', 'Pizza Palmito a Bolonhesa', 42.9),
(50, 'Lasanha', 'Lasanha à Bolonhesa', 26.9),
(51, 'Lasanha', 'Lasanha Frango à Catupiry', 26.9),
(52, 'Macarrão na Chapa', 'Macarrão à Bolonhesa', 17.9),
(53, 'Macarrão na Chapa', 'Macarrão ao Alho e Óleo', 17.9),
(54, 'Pastelão', 'Pastel de Carne', 8),
(55, 'Pastelão', 'Pastel de Frango', 8),
(56, 'Pastelão', 'Pastel Napolitano', 8),
(57, 'Pastelão', 'Pastel de Frango com Catupiry', 9.4),
(58, 'Pastelão', 'Pastel de Queijo (Mussarela)', 8),
(59, 'Pastelão', 'Pastel de Churros', 9.4),
(60, 'Porções', 'Porção de Batata Frita 400gr', 18),
(61, 'Porções', 'Porção de Batata Frita 400gr com Mussarela e Bacon', 22.9),
(62, 'Porções', 'Quibinho (12 unidades)', 14.5),
(63, 'Porções', 'Strogonoff de frango', 17.9),
(64, 'Porções', 'Porção de Filé Mignon acebolado com fritas e mussarela', 89.9),
(65, 'Porções', 'Tilápia c/ fritas', 59.9),
(66, 'Porções', 'Contra Filé c/ fritas', 69.9),
(67, 'Porções', 'Picanha c/ fritas', 79.9),
(68, 'Creme de Açai', 'Creme de açai (300g)', 13.9),
(69, 'Creme de Açai', 'Creme de açai (500g)', 17.9),
(70, 'Creme de Açai', 'Creme de açai (1kg)', 32.9),
(71, 'Sucos', 'Suco de laranja natural (300 ml)', 7),
(72, 'Sucos', 'Jarra de suco de laranja natural (700 ml)', 12.9),
(73, 'Sucos', 'Jarra de suco de laranja natural (1500 ml)', 22.9),
(74, 'Sucos', 'Limonada suiça (300 ml)', 7),
(75, 'Sucos', 'Jarra de Limonada suiça (700 ml)', 12.9),
(76, 'Sucos', 'Jarra de Limonada suiça (1500 ml)', 22.9),
(77, 'Sucos', 'Acerola', 7),
(78, 'Sucos', 'Abacaxi', 7),
(79, 'Sucos', 'Abacaxi com hortelã', 7),
(80, 'Sucos', 'Morango', 7),
(81, 'Sucos', 'Maracujá', 7),
(82, 'Sucos', 'Graviola', 7),
(83, 'Sucos', 'Cacau', 7),
(84, 'Sucos', 'Açaí', 8.9),
(85, 'Bebidas Diversas', 'Refrigerante Ks', 5),
(86, 'Bebidas Diversas', 'Refrigerante Lata', 6),
(87, 'Bebidas Diversas', 'Refrigerante (600 ml)', 7),
(88, 'Bebidas Diversas', 'Refrigerante (2 litros)', 10),
(89, 'Bebidas Diversas', 'Refrigerante (1 litro)', 7.5),
(90, 'Bebidas Diversas', 'Refrigerante Coca-Cola (2 litros)', 11.5),
(91, 'Bebidas Diversas', 'Suco Lata', 7),
(92, 'Bebidas Diversas', 'Água sem gás', 2.5),
(93, 'Bebidas Diversas', 'Água com gás', 3),
(94, 'Bebidas Diversas', 'Cerveja latão', 6),
(95, 'Bebidas Diversas', 'Cerveja sem álcool lata', 6),
(96, 'Bebidas Diversas', 'Energético', 12),
(97, 'Bebidas Diversas', 'Smiirnoff Ice', 12),
(98, 'Bebidas Diversas', 'Cerveja long neck', 8);
